-- CREATE USERS TABLE
CREATE TABLE `users` (`id` INT NOT NULL AUTO_INCREMENT, `name` VARCHAR(50) NOT NULL, PRIMARY KEY(`id`)) ENGINE = InnoDB;

-- INSERT USER TEST DATA
INSERT INTO `users`(name)  VALUES ('Jose'), ('Isaac'), ('Natali');

